---
title: "RWorksheet_Laguda#3a"
author: "Rey-Ann S. Laguda"
date: "2023-10-11"
output: pdf_document
---

#1. VECTORS
#A
```{r number1a}
first_eleven <- LETTERS[1:11]
first_eleven
```

#B
```{r number1b}
odd_letters <- LETTERS[seq(1,25,2)] 
odd_letters
```
#C 
``` {r number1c}
vowels <- c(letters[which(letters %in% c("a","e","i","o","u"))], 
            LETTERS[which(LETTERS %in% c("A","E","I","O","U"))])
vowels
```
#D.
``` {r number1d}
last5letter <- tail(letters, 5)
last5letter
```

#E
```{r number1e}
letterbetween15to24 <- letters[15:24]
letterbetween15to24
```
#NUMBER 2
#A.
``` {r number2a}
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city
```
#B
``` {r number2b}
temp <- c(42, 39, 34, 34, 30, 27)
temp
```
#C
``` {r number2c}
df <- data.frame(city, temp)
df
```
#D
``` {r nnumber2d}
names(df) <- c("City", "Temperature")
df
```
#E
``` {r number2e}
str(df)
```
#F
``` {r number2f}
df[3:4,]
```
#G
``` {r number2g}
highest_temp_city <- df$City[which.max(df$Temperature)]
lowest_temp_city <- df$City[which.min(df$Temperature)]
highest_temp_city
lowest_temp_city
```
#2 MATRICES
#A
``` {r number#2a}
m <- matrix(c(1:8,11:14),ncol = 4, nrow = 3)
m
``` 
#B
``` {r number#2b}
matrix(c(1:8,11:14), ncol = 4, nrow = 3)*2
```
#C
``` {r number#c}
matrix(c(1:8,11:14), ncol = 4, nrow = 3)[2,]
```
#D
``` {r number#d}
matrix(c(1:8,11:14), ncol = 4, nrow = 3)[1:2,c(3,4)]
```








