---
title: "RWorksheet_Laguda#4a"
author: "Rey-Ann S. Laguda"
date: "2023-10-25"
output:
  pdf_document: default
  word_document: default
---

#Number1
``` {r number1}
df <- data.frame (
  ShoesSize = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0),
  Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0),
  Gender = c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F","M", "F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M"))
df
```
#B
``` {r number1b}
male_subset <- df[df$Gender == "M", c("ShoesSize", "Height")]
female_subset <- df[df$Gender == "F", c("ShoesSize", "Height")]
male_subset
female_subset
```

#c
``` {r number1c}
 mean(df$ShoesSize)
mean(df$Height)
```

#d
# Yes, there is relationship between the height and shoe size, the more taller they are, the longer their size. 

#Number 2
``` {r number2}
months <- c("March","April","January","November","January",
"September","October","September","November","August",
"January","November","November","February","May","August", "July","December","August","August","September","November","February",
"April")
months
factor_months_vector <- factor(months)
factor_months_vector
```

#3
``` {r number3}
summary(months)
summary(factor_months_vector)
```

#Number 4
``` {r number4}
direction_vector <- c("East", "West", "North")
frequency_vector <- c(1, 4, 3)
factor_data <- factor(c(direction_vector, frequency_vector))
new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)
```

#Number 5
``` {r number5}
student_table <- read.table(file = 'import_march.csv', header = TRUE, sep = ',')
student_table
```

#Number6
``` {r number6}
user_input <- as.numeric(readline ("Enter a number between 1 to 50: "))
if (!is.na(user_input))
if (user_input < 1 && user_input >50) {
  cat("The number selected is beyond the range of 1 to 50\n")
} else if (user_input == 20) {
  cat("TRUE\n")
} else {
  cat("The chosen number is: ", user_input, "\n")
}
```
#7 
``` {r number7}
minimum_bills_needed <- function(price) {
 
  bill_denominations <- c(1000, 500, 200, 100, 50)
  
 
  bill_counts <- integer(length(bill_denominations))
  
  
  for (i in 1:length(bill_denominations)) {
 
    bill_counts[i] <- price %/% bill_denominations[i]
    
   
    price <- price %% bill_denominations[i]
  }
  cat("Minimum number of bills needed to purchase the snack:\n")
  for (i in 1:length(bill_denominations)) {
    cat(bill_denominations[i], "peso bills: ", bill_counts[i], "\n")
  }
}

# Example usage:
price_of_snack <- 750 
minimum_bills_needed(price_of_snack)

```

#8 
#A
``` {r number8a}
students <- data.frame(
  Name = c("Annie" , "Thea", "Steve", "Hanna"),
  Grade1 = c(85,65,75,95),
  Grade2 = c(65,75,55,75),
  Grade3 = c(85,90,80,100),
  Grade4 = c(100,90,85,90)
)
students
```

#B
``` {r number8b}
students$Average <- (students$Grade1 + students$Grade2 + students$Grade3 + students$Grade4) / 4

for (i in 1:nrow(students)) {
  average <- (students$Grade1[i] + students$Grade2[i] + students$Grade3[i] + students$Grade4[i]) / 4
  count <- 0
  total_average <- 0
  if (students$Grade4[i] > 90) {
    cat(students$Name[i], "'s average grade this semester is", average, ".\n")
    total_average <- total_average + average
    count <- count + 1
  }
}

if (count > 0) {
  overall_average <- total_average / count
  cat("The overall average for high-achieving students is", overall_average, ".\n")
} else {
  cat("No high-achieving students found.\n")
}
```

#C
``` {r number8c}
students$Average <- rowMeans(students[, 2:5])
difficult_tests <- which(students$Average < 80)

if (length(difficult_tests) > 0) {
  cat("The following tests were difficult for one or more students:\n")
  for (i in difficult_tests) {
    cat("The ", i, if (i == 2) "nd" else if (i == 3) "rd" else "th", " test was difficult.\n")
  }
} else {
  cat("No test was difficult for any student.\n")
}

```

#D
``` {r number8d}
highest_grades <- numeric(length(students$Name))

for (i in 1:nrow(students)) {
  student_name <- students$Name[i]
  semester_grades <- students[i, 2:5]
  highest_grade <- -Inf
  
  for (grade in semester_grades) {
    if (grade > highest_grade) {
      highest_grade <- grade
    }
  }
  
  highest_grades[i] <- highest_grade
  
  if (highest_grade > 90) {
    cat(student_name, "'s highest grade this semester is ", highest_grade, ".\n")
  }
}
```










