---
title: "RWorksheet_Laguda#4a"
author: "Rey-Ann S. Laguda"
date: "2023-10-25"
output: pdf_document
---

#Number1
``` {r number1}
df <- data.frame (
  ShoesSize = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0),
  Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0),
  Gender = c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F","M", "F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M"))
df
```
#B
``` {r number1b}
male_subset <- df[df$Gender == "M", c("ShoesSize", "Height")]
female_subset <- df[df$Gender == "F", c("ShoesSize", "Height")]
male_subset
female_subset
```

#c
``` {r number1c}
 mean(df$ShoesSize)
mean(df$Height)
```

#d
# Yes, there is relationship between the height and shoe size, the more taller they are, the longer their size. 

#Number 2
``` {r number2}
months <- c("March","April","January","November","January",
"September","October","September","November","August",
"January","November","November","February","May","August", "July","December","August","August","September","November","February",
"April")
months
factor_months_vector <- factor(months)
factor_months_vector
```

#3
``` {r number3}
summary(months)
summary(factor_months_vector)
```

#Number 4
``` {r number4}
direction_vector <- c("East", "West", "North")
frequency_vector <- c(1, 4, 3)
factor_data <- factor(c(direction_vector, frequency_vector))
new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)
```

#Number 5
``` {r number5}
library(readxl)
file_path <- "import_march.csv"
data <- read_csv(file_path)
View(data)
```

#Number6
``` {r number6}
user_input <- as.numeric(readline ("Enter a number between 1 to 50: "))
if (!is.na(user_input))
if (user_input < 1 || user_input >50) {
  cat("The number selected is beyond the range of 1 to 50\n")
} else if (user_input == 20) {
  cat("TRUE\n")
} else {
  cat("The chosen number is: ", user_input, "\n")
}
```

















